Fix/ignore badook tests
badook-ai/badook-airflow pull request #16
Opened 2021-11-09 04:08 UTC by roadan

2021-11-09 04:36 UTC, estiller requested changes
Please fix the formatter and linter issues first...

2021-11-09 06:30 UTC, estiller requested changes
Please see comments inside.

Also - all the `.DS_Store` files should not be in source control. Please remove them. We can consider adding the `macOS` category to our generated `.gitignore` file (like [this](https://www.toptal.com/developers/gitignore/api/python,visualstudiocode,pycharm+all,macos)).

2021-11-09 06:30 UTC, estiller commented on pyproject.toml
> +pylint = "^2.10.2"
Why are you reverting versions of packages? Please undo this.

2021-11-09 06:30 UTC, estiller commented on pyproject.toml
> +autopep8 = "^1.5.7"
Why are you reverting versions of packages? Please undo this.

2021-11-09 06:30 UTC, estiller commented on badook_airflow/hooks/badook_hook.py
> +            # BadookBaseTestResult.results
Why did you add this commented line?

2021-11-09 06:30 UTC, estiller commented on badook_airflow/hooks/badook_hook.py
> +    def get_connection_form_widgets() -> Dict[str, Any]:
What is this method and how is it related to ignoring badook tests?

2021-11-10 00:43 UTC, roadan commented on badook_airflow/hooks/badook_hook.py
> +    def get_connection_form_widgets() -> Dict[str, Any]:
This is weird, this method is a part of the Airflow connection setup and has been around for a long time, it must have been deleted somehow but since I'm the main maintainer here, I think that was dome by mistake, so I suggest keeping it.

2021-11-10 00:58 UTC, estiller approved these changes

2021-11-10 02:17 UTC, merged